/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;


import br.com.adilson.util.Extenso;
import br.com.adilson.util.PrinterMatrix;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
public class NewJFrame extends javax.swing.JFrame {

    DefaultTableModel model;
    

    public NewJFrame() {

        initComponents();
        String[] titulos = {"NoPedido", "NoEmpleado", "TotalVenta", "Fecha"};
        model = new DefaultTableModel(null, titulos);
        jTable1.setModel(model);
        
         
        
        mostrarDatos();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noEmpleadoLabel = new javax.swing.JLabel();
        empladoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        editarRepartidor = new javax.swing.JMenu();
        repartidoresMenu = new javax.swing.JMenuItem();
        corteRepartidores = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMANDERO COLOSO");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);
        setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        setForeground(java.awt.Color.white);
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Logo-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, 190));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setText("COMANDERO COLOSO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 11, 507, 68));

        noEmpleadoLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        noEmpleadoLabel.setText("# Empleado");
        getContentPane().add(noEmpleadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 323, -1, -1));

        empladoTextField.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        empladoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empladoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empladoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(empladoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 370, 167, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("# Pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 323, -1, -1));

        jTextField1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 167, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("Total ticket");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 323, -1, -1));

        jTextField2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 181, -1));

        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/save.png"))); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 56));

        jButton2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/modify.png"))); // NOI18N
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, 56));

        jButton3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Spring\\JavaApplication2\\src\\javaapplication2\\delete.png")); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 56));

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setColumnHeaderView(jTable1);
        jScrollPane2.setWheelScrollingEnabled(false);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAlignmentX(1.0F);
        jTable1.setAlignmentY(1.0F);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setDropMode(javax.swing.DropMode.ON);
        jTable1.setFillsViewportHeight(true);
        jTable1.setFocusCycleRoot(true);
        jTable1.setName(""); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(800, 100000));
        jTable1.setRowHeight(40);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTable1MouseWheelMoved(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 646, 550));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Desarrollado por Irán García para Pollos Coloso. Derechos reservados.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 378, 23));

        jButton4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/clear.png"))); // NOI18N
        jButton4.setLabel("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 181, 56));

        jButton5.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search.png"))); // NOI18N
        jButton5.setText("BUSCAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 167, 56));

        editarRepartidor.setBackground(new java.awt.Color(255, 255, 255));
        editarRepartidor.setForeground(new java.awt.Color(3, 3, 3));
        editarRepartidor.setText("Usuarios");

        repartidoresMenu.setText("Usuarios");
        repartidoresMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repartidoresMenuActionPerformed(evt);
            }
        });
        editarRepartidor.add(repartidoresMenu);

        corteRepartidores.setText("Corte de repartidores");
        corteRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corteRepartidoresActionPerformed(evt);
            }
        });
        editarRepartidor.add(corteRepartidores);

        jMenuBar1.add(editarRepartidor);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void repartidoresMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repartidoresMenuActionPerformed
        conexion objConexion = new conexion();
        JPasswordField contraseña = new JPasswordField();
        String contra = "";
        int user = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese su número de usuario"));
        if (JOptionPane.showConfirmDialog(null, contraseña, "Ingrese contraseña", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            contra = new String(contraseña.getPassword());
        }
        String strSentenciapass = "SELECT NoEmpleado, Contrasena, Administrador FROM Empleados WHERE NoEmpleado= " + user + " AND Contrasena ='" + contra + "'" + "AND Administrador= '"+1+"';";
        int resulta = objConexion.ejecutarSentenciaPermiso(strSentenciapass);
        if (resulta == 1) {
            frameUsuario f = new frameUsuario();
            f.setVisible(true);

        }


    }//GEN-LAST:event_repartidoresMenuActionPerformed

    private void corteRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corteRepartidoresActionPerformed
        CorteEmpleados c = new CorteEmpleados();
        c.setVisible(true);
       
    }//GEN-LAST:event_corteRepartidoresActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
//Boton de insertar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        conexion objConexion = new conexion();
        pedidosBL oPedidos = recuperarDatosGUI();
        String strSentenciaInsert = "INSERT INTO Pedidos (NoPedido,Noempleado,TotalVenta,Fecha) values(" + oPedidos.getNoPedido() + "," + oPedidos.getNoEmpleado() + "," + oPedidos.getTotalVenta() + ",datetime('now', 'localtime'));";
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        limpiarTabla();
        limpiarCampos();
        mostrarDatos();

    }//GEN-LAST:event_jButton1ActionPerformed
    public pedidosBL recuperarDatosGUI() //Este metodo recupera los datos en los Textfield para ser seleccionados
    {
        pedidosBL oPedidos = new pedidosBL();
        try {

            int NoPedido = (jTextField1.getText().isEmpty()) ? 0 : Integer.parseInt(jTextField1.getText());
            oPedidos.setNoPedido(NoPedido);
            oPedidos.setNoEmpleado(Integer.parseInt(empladoTextField.getText()));
            oPedidos.setTotalVenta(Integer.parseInt(jTextField2.getText()));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingresa solamente NUMEROS y no dejes ESPACIOS EN BLANCO");
        }

        return oPedidos;

    }

    //Muestra los datos de la base de datos en el jTable1
    public void mostrarDatos() {

        conexion objConexion = new conexion();
        try {
            
            LocalDateTime ldt = LocalDateTime.now();
            String Fecha=DateTimeFormatter.ofPattern("yyyy-MM-dd", Locale.ENGLISH).format(ldt);
            System.out.println(Fecha);

            ResultSet resultado = objConexion.consultarRegistros("SELECT *FROM Pedidos WHERE Fecha BETWEEN '"+Fecha+" 00:00:00' AND '"+Fecha+" 23:59:59'");
            while (resultado.next()) {
                Object[] oUsuario = {resultado.getString("NoPedido"), resultado.getString("NoEmpleado"), resultado.getString("TotalVenta"), resultado.getString("Fecha")};
                model.addRow(oUsuario);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void mostrarDatosUsuarios() {

        conexion objConexion = new conexion();
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Empleados");
            while (resultado.next()) {
                Object[] oUsuario = {resultado.getString("NoEmpleado"), resultado.getString("Contraseña"), resultado.getString("Nombre Empleado"), resultado.getString("ApellidoEmpleado")};
                model.addRow(oUsuario);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void busquedaDatos() {

        conexion objConexion = new conexion();

        try {
            int result = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de comanda"));
            ResultSet resultado = objConexion.consultarRegistros("SELECT NoPedido, NoEmpleado, TotalVenta, Fecha FROM Pedidos WHERE NoPedido=" + result);

            while (resultado.next()) {
                Object[] oUsuario = {resultado.getString("NoPedido"), resultado.getString("NoEmpleado"), resultado.getString("TotalVenta"), resultado.getString("Fecha")};
                model.addRow(oUsuario);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese solamente números y no deje espacios en blanco");
            mostrarDatos();
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        pedidosBL oPedidos = recuperarDatosGUI();
        String strSentenciaInsert = "UPDATE Pedidos SET NoEmpleado = " + empladoTextField.getText() + ",TotalVenta=" + jTextField2.getText() + " WHERE NoPedido=" + jTextField1.getText();
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        limpiarTabla();
        limpiarCampos();
        mostrarDatos();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void empladoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empladoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empladoTextFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            jTextField1.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            empladoTextField.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            jTextField2.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        conexion objConexion = new conexion();
        pedidosBL oPedidos = recuperarDatosGUI();
        String strSentenciaInsert = "DELETE FROM Pedidos WHERE NoPedido=" + jTextField1.getText();
        JPasswordField contraseña = new JPasswordField();
        String contra = "";
        int user = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese su número de usuario"));
        if (JOptionPane.showConfirmDialog(null, contraseña, "Ingrese contraseña", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            contra = new String(contraseña.getPassword());
        }
        String strSentenciapass = "SELECT NoEmpleado, Contrasena, Administrador FROM Empleados WHERE NoEmpleado= " + user + " AND Contrasena ='" + contra + "'" + "AND Administrador= '"+1+"';";
        objConexion.ejecutarSentenciaSQL2(strSentenciapass, strSentenciaInsert);
        limpiarTabla();
        limpiarCampos();
        mostrarDatos();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTable1MouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         conexion objConexion = new conexion();
        String strSentenciaInsert = "DELETE FROM Pedidos";
        JPasswordField contraseña = new JPasswordField();
        String contra = "";
        int user = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese su número de usuario"));
        if (JOptionPane.showConfirmDialog(null, contraseña, "Ingrese contraseña", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            contra = new String(contraseña.getPassword());
        }
        String strSentenciapass = "SELECT NoEmpleado, Contrasena, Administrador FROM Empleados WHERE NoEmpleado= " + user + " AND Contrasena ='" + contra + "'" + "AND Administrador= '"+1+"';";
        objConexion.ejecutarSentenciaSQL2(strSentenciapass, strSentenciaInsert);
        limpiarTabla();
        limpiarCampos();
        mostrarDatos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        limpiarCampos();
        busquedaDatos();


    }//GEN-LAST:event_jButton5ActionPerformed
    public void limpiarTabla() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

    public void limpiarCampos() {
        jTextField1.setText("");
        empladoTextField.setText("");
        jTextField2.setText("");
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        try
        {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        }catch (Exception e)
                {
                    
                }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem corteRepartidores;
    private javax.swing.JMenu editarRepartidor;
    private javax.swing.JTextField empladoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel noEmpleadoLabel;
    private javax.swing.JMenuItem repartidoresMenu;
    // End of variables declaration//GEN-END:variables

    private void NewJDialog() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
